#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  3 22:06:15 2017

@author: archit
"""

import pandas as pd
import surprise 
    
from surprise import evaluate, print_perf
from surprise import KNNWithMeans
from surprise import Dataset
from surprise import Reader
from surprise import GridSearch



data1 = pd.read_csv("/Users/archit/Desktop/archit MSOR/Fall 2017 Subjects/Personalization theory/Projects/personalization-theory-master/sampled_data.csv")
    
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(data1[['User', 'Item', 'Rating']], reader)
data.split(2)
    
    
#print data.head()

param_grid = {'k': [20,30, 40],
             'sim_options': {'name': ['msd', 'cosine'],
                              'min_support': [10],
                              'user_based': [False]}
              }
              
                   
grid_search = GridSearch(KNNWithMeans, param_grid, measures=['RMSE', 'MAE'])
grid_search.evaluate(data)

results_df = pd.DataFrame.from_dict(grid_search.cv_results)
print(results_df)





    
    


        
        
        
        

